### ISSUE TITLE
Potential Bug: Missing '/public' Prefix in QRCode Logo Path (QRCode.php Line 175)

### ISSUE THREAD

**Issue by moritz-sauer-13** [xddesigners/silverstripe-qr-code-generator#1]
Hello,

I believe I may have come across a potential issue in the QRCode.php file, specifically in Line 175, where the path is configured for the Logo. It appears that there might be a missing "/public" prefix in front of the "/assets" folder. Could you kindly confirm if this omission is intentional or if there might be an explanation that I'm currently overlooking?

**Comment by RVXD** [comment]
Hi Moritz,
thanks for your reporting your issue. At the time the module was developed we were not using the public folder. I will try to look into making this configurable.
Regards,
Remy

**Comment by moritz-sauer-13** [comment]
Thank you very much! 
I've also noticed that sometimes the URL for the QR code is missing a / between the top level domain and the QR URL.
Is there a way to make this configurable as well?
Kind regards,
Moritz

**Comment by RVXD** [comment]
Hi Moritz,
will have to put some time into this. Currently quite busy before christmas period. If you have suggestions for file changes, feel free to make a PR.
Remy

**Comment by moritz-sauer-13** [comment]
Hello Remy,

Thank you for your message. I understand that the pre-Christmas period is particularly busy. I'm happy to review the suggested changes and will prepare a PR accordingly.
Moritz

**Comment by RVXD** [comment]
Ah, that would be nice. Thanks!
